export const FIRE_CHECK_START = "FIRE_CHECK";
export const FIRE_CHECK_POS = "FIRE_CHECK_POS";
export const FIRE_CHECK_NEG = "FIRE_CHECK_NEG";

export const TYPE_CHECK_START = "TYPE_CHECK_START";
export const TYPE_CHECK_POS = "TYPE_CHECK_POS";
export const TYPE_CHECK_NEG = "TYPE_CHECK_NEG";

// Register a user

export const REGISTER_PROCESS_START = "REGISTER_PROCESS_START";
export const REGISTER_PROCESS_FAIL = "REGISTER_PROCESS_FAIL";
export const REGISTER_PROCESS_SUCCESS = "REGISTER_PROCESS_SUCCESS";

export const REGISTER_FIREBASE_START = "REGISTER_FIREBASE_START";
export const REGISTER_FIREBASE_FAIL = "REGISTER_FIREBASE_FAIL";
export const REGISTER_FIREBASE_SUCCESS = "REGISTER_FIREBASE_SUCCESS";

export const REGISTER_MONGO_START = "REGISTER_MONGO_START";
export const REGISTER_MONGO_FAIL = "REGISTER_MONGO_FAIL";
export const REGISTER_MONGO_SUCCESS = "REGISTER_MONGO_SUCCESS";

export const PICK_TYPE_START = "PICK_TYPE_START";
export const PICK_TYPE_FAIL = "PICK_TYPE_FAIL";
export const PICK_TYPE_SUCCESS = "PICK_TYPE_SUCCESS";

export const CHECKING_USER_START = "CHECKING_USER_START";
export const CHECKING_USER_FAIL = "CHECKING_USER_FAIL";
export const CHECKING_USER_SUCCESS = "CHECKING_USER_SUCCESS";
