export const FIRE_LOG_START = "FIRE_LOGIN_START";
export const FIRE_LOG_FAIL = "FIRE_LOGIN_FAIL";
export const FIRE_LOG_SUCCESS = "FIRE_LOGIN_SUCCESS";

export const MAKE_MANAGER = "MAKE_MANAGER";
export const MAKE_TRANSPORTER = "MAKE_TRANSPORTER";
